## Defining Variables

In [15]:
"Hello World"

'Hello World'

In [2]:
greeting = "Hello World"

In [3]:
greeting

'Hello World'

In [4]:
greeting = "Hello World"
greeting

'Hello World'

In [5]:
print(greeting)

Hello World


## Basic Math

In [7]:
a = 2
b = 15

In [8]:
a + b

17

In [9]:
my_sum = a + b

In [10]:
my_sum

17

In [11]:
my_product = a * b
my_product

30

## Import Libraries

In [12]:
import numpy as np

In [13]:
ages_list = [25, 30, 36, 40, 45]

In [14]:
ages = np.array(ages_list)

In [16]:
ages

array([25, 30, 36, 40, 45])

In [17]:
ages = np.array([25, 30, 35, 40, 45, 50, 55])
ages

array([25, 30, 35, 40, 45, 50, 55])

In [18]:
ages + 2

array([27, 32, 37, 42, 47, 52, 57])

In [19]:
ages * 2

array([ 50,  60,  70,  80,  90, 100, 110])

In [21]:
# Indexing
ages[-1], ages[0]

(55, 25)

In [22]:
ages[0:4]

array([25, 30, 35, 40])

In [23]:
ages[:4]

array([25, 30, 35, 40])

In [24]:
ages[1:4]

array([30, 35, 40])

In [25]:
ages[::2]

array([25, 35, 45, 55])

In [27]:
ages[::-1]

array([55, 50, 45, 40, 35, 30, 25])

In [29]:
ages[ages < 40]

array([25, 30, 35])

In [30]:
ages < 40

array([ True,  True,  True, False, False, False, False])

In [33]:
ages[(ages > 25) & (ages < 50)]

array([30, 35, 40, 45])

## Statistics

In [36]:
ages_mean = np.mean(ages)
ages

array([25, 30, 35, 40, 45, 50, 55])